
export type User = {
  name: string;
  avatarUrl: string;
  initials: string;
};

export type Incident = {
  id: string;
  timestamp: string;
  domain: string;
  userIdHash?: string;
  types: string[];
  action: 'Blocked' | 'Warned' | 'Allowed';
  riskScore?: number;
  details?: string; // This will be generated by the AI
};

export type PolicyPack = {
  id: string;
  name: string;
  description: string;
  rules: string[];
};

export type EventsByTimeData = {
  date: string;
  Blocked: number;
  Warned: number;
  Allowed: number;
};

export type LeaksByTypeData = {
  type: string;
  count: number;
};

export type LeaksByDomainData = {
  domain: string;
  count: number;
};
