"use client"

import { useState } from "react"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { PolicyPack } from "@/lib/types"
import { explainPolicyPack } from "@/ai/flows/explain-policy-pack"
import { Skeleton } from "../ui/skeleton"

export function PoliciesClient({ data }: { data: PolicyPack[] }) {
  const [selectedPolicy, setSelectedPolicy] = useState<PolicyPack | null>(null)
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [aiExplanation, setAiExplanation] = useState<string>("")
  const [isLoadingExplanation, setIsLoadingExplanation] = useState(false)

  const handleViewExplanation = async (policy: PolicyPack) => {
    setSelectedPolicy(policy)
    setIsDialogOpen(true)
    setAiExplanation("")
    setIsLoadingExplanation(true)
    try {
      const result = await explainPolicyPack({ policyPackDescription: policy.description })
      setAiExplanation(result.explanation)
    } catch (error) {
      console.error("Failed to generate AI explanation:", error)
      setAiExplanation("Could not generate explanation at this time.")
    } finally {
      setIsLoadingExplanation(false)
    }
  }

  return (
    <>
      <Card>
        <CardHeader>
            <CardTitle>Policy Packs</CardTitle>
            <CardDescription>Manage and understand the rule sets that power Airlock DLP.</CardDescription>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full">
            {data.map((pack) => (
              <AccordionItem value={pack.id} key={pack.id}>
                <AccordionTrigger className="text-lg font-headline hover:no-underline">
                  {pack.name}
                </AccordionTrigger>
                <AccordionContent className="pt-2">
                  <p className="mb-4 text-muted-foreground">{pack.description}</p>
                  <div className="mb-4">
                    <h4 className="font-semibold mb-2">Rules</h4>
                    <div className="flex flex-wrap gap-2">
                      {pack.rules.map((rule) => (
                        <Badge variant="secondary" key={rule} className="font-normal">{rule}</Badge>
                      ))}
                    </div>
                  </div>
                  <Button onClick={() => handleViewExplanation(pack)} size="sm" variant="outline">
                    Explain with AI
                  </Button>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>
      
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[525px]">
          <DialogHeader>
            <DialogTitle>AI Explanation: {selectedPolicy?.name}</DialogTitle>
            <DialogDescription>
              This explanation is generated by AI to help you understand the purpose of this policy pack.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {isLoadingExplanation ? (
                <div className="space-y-2">
                    <Skeleton className="h-4 w-full" />
                    <Skeleton className="h-4 w-full" />
                    <Skeleton className="h-4 w-[75%]" />
                </div>
            ) : (
                <p className="text-sm text-muted-foreground">{aiExplanation}</p>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
